const EVENT_RUN_SCRIPT = 'RUN_SCRIPT'
const EVENT_STOP_SCRIPT = 'STOP_SCRIPT'
const EVENT_PRINT_LOG = 'PRINT_LOG'
const EVENT_PRINT_TERMINAL = 'PRINT_TERMINAL'
const EVENT_LISTEN_KEYWORD = 'LISTEN_KEYWORD'
const EVENT_LISTEN_KEYWORD_RESULT = 'LISTEN_KEYWORD_RESULT'
const EVENT_LISTEN_CLEANUP = 'LISTEN_CLEANUP'
const EVENT_TERMINAL_INPUT = 'TERMINAL_INPUT'
const EVENT_TERMINAL_OUTPUT = 'TERMINAL_OUTPUT'

export {
  EVENT_RUN_SCRIPT,
  EVENT_STOP_SCRIPT,
  EVENT_PRINT_LOG,
  EVENT_PRINT_TERMINAL,
  EVENT_LISTEN_KEYWORD,
  EVENT_LISTEN_KEYWORD_RESULT,
  EVENT_LISTEN_CLEANUP,
  EVENT_TERMINAL_INPUT,
  EVENT_TERMINAL_OUTPUT
}
