const EVENT_ASYNC_MSG = 'ASYNC_MSG'
const EVENT_ASYNC_REPLY = 'ASYNC_REPLY'
const EVENT_RUN_SCRIPT = 'RUN_SCRIPT'
const EVENT_STOP_SCRIPT = 'STOP_SCRIPT'
const EVENT_PRINT_LOG = 'PRINT_LOG'
const EVENT_PRINT_TERMINAL = 'PRINT_TERMINAL'
const EVENT_LISTEN_KEYWORD = 'LISTEN_KEYWORD'
const EVENT_LISTEN_KEYWORD_RESULT = 'LISTEN_KEYWORD_RESULT'
const EVENT_LISTEN_CLEANUP = 'LISTEN_CLEANUP'
const EVENT_TERMINAL_INPUT = 'TERMINAL_INPUT'
const EVENT_TERMINAL_OUTPUT = 'TERMINAL_OUTPUT'
const EVENT_UPDATE = 'IS_UPDATE_NOW'
const EVENT_CHECK_FOR_UPDATE = 'CHECK_FOR_UPDATE'

const MSG_UPDATE_NOW = 0
const MSG_UPDATE_ON_QUIT = 1
const MSG_NO_UPDATE = 2

export {
  EVENT_ASYNC_MSG,
  EVENT_ASYNC_REPLY,
  EVENT_RUN_SCRIPT,
  EVENT_STOP_SCRIPT,
  EVENT_PRINT_LOG,
  EVENT_PRINT_TERMINAL,
  EVENT_LISTEN_KEYWORD,
  EVENT_LISTEN_KEYWORD_RESULT,
  EVENT_LISTEN_CLEANUP,
  EVENT_TERMINAL_INPUT,
  EVENT_TERMINAL_OUTPUT,
  EVENT_UPDATE,
  EVENT_CHECK_FOR_UPDATE,
  MSG_UPDATE_NOW,
  MSG_UPDATE_ON_QUIT,
  MSG_NO_UPDATE
}
